dist: focal
language: node_js
node_js:
  - 18
before_install:
  - sudo apt-get install cppcheck
  - pip3 install conan cpplint
  - conan profile new --detect default
  - conan profile update settings.compiler.libcxx=libstdc++11 default
script:
  - npm run coverage
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_API_TOKEN
  on:
    tags: true
    branch: main
addons:
  apt:
    update: true
